# PostgreSQL datasource (change for votre environnement)
spring.datasource.url=jdbc:postgresql://localhost:5432/confdocdb
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.root=INFO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Keystore settings (le fichier est généré automatiquement dans data/ si absent)
app.keystore.path=keystore/keystore.jks
app.keystore.password=Genius@Keypass1
app.keystore.alias=jwtkey
app.keystore.key-password=Genius@Keypass1

# Storage directory
app.storage.dir=keystore/storage
app.supabase.url=https://aqzawbrlhzumygbzeoyo.supabase.co
app.supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxemF3YnJsaHp1bXlnYnplb3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NjUyOTIsImV4cCI6MjA4MDQ0MTI5Mn0.53nqHoxLfus9Pk88OiRTAV7w5nO096evqMFEExAg0R8
app.supabase.bucket=documents
app.supabase.secure.path=secure

# JWT
app.jwt.expiration-ms=3600000

# HTTPS configuration (desactiver/activer selon besoin)
#server.port=8443
server.port=8080
server.ssl.enabled=false
server.ssl.key-store=${app.keystore.path}
server.ssl.key-store-password=${app.keystore.password}
server.ssl.key-password=${app.keystore.key-password}
server.ssl.key-store-type=JKS