# ============================
# DATABASE CONFIG
# ============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ============================
# KEYSTORE CONFIG
# ============================
app.keystore.path=${APP_KEYSTORE_PATH}
app.keystore.password=${APP_KEYSTORE_PASSWORD}
app.keystore.alias=${APP_KEYSTORE_ALIAS}
app.keystore.key-password=${APP_KEYSTORE_KEY_PASSWORD}

# ============================
# STORAGE
# ============================
app.storage.dir=${APP_STORAGE_DIR}

# ============================
# SUPABASE
# ============================
app.supabase.url=${SUPABASE_URL}
app.supabase.key=${SUPABASE_KEY}
app.supabase.bucket=${SUPABASE_BUCKET}
app.supabase.secure.path=${SUPABASE_SECURE_PATH}

# ============================
# JWT
# ============================
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

# ============================
# SERVER
# ============================
server.port=8080
server.ssl.enabled=false
server.ssl.key-store=${APP_KEYSTORE_PATH}
server.ssl.key-store-password=${APP_KEYSTORE_PASSWORD}
server.ssl.key-password=${APP_KEYSTORE_KEY_PASSWORD}
server.ssl.key-store-type=JKS

# ============================
# CORS
# ============================
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# ============================
# LOGGING
# ============================
logging.level.root=INFO

# Page racine
spring.web.resources.add-mappings=true

# Actuator accessible sans Auth mais en lecture seule
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Désactiver totalement la sécurité sur actuator
management.endpoints.web.base-path=/actuator
