spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

logging.level.root=INFO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Keystore settings
app.keystore.path=${APP_KEYSTORE_PATH}
app.keystore.password=${APP_KEYSTORE_PASSWORD}
app.keystore.alias=${APP_KEYSTORE_ALIAS}
app.keystore.key-password=${APP_KEYSTORE_KEY_PASSWORD}

# Storage directory
app.storage.dir=${APP_STORAGE_DIR}

# Supabase
app.supabase.url=${SUPABASE_URL}
app.supabase.key=${SUPABASE_KEY}
app.supabase.bucket=${SUPABASE_BUCKET}
app.supabase.secure.path=${SUPABASE_SECURE_PATH}

# JWT
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

server.port=8080
server.ssl.enabled=false
server.ssl.key-store=${app.keystore.path}
server.ssl.key-store-password=${app.keystore.password}
server.ssl.key-password=${app.keystore.key-password}
server.ssl.key-store-type=JKS

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
